services:
  gms-proj-postgres:
    container_name: gms-proj-postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - gms-proj-data:/var/lib/postgresql/data
    networks:
      - gms-proj-net
  gms-proj-minio:
    restart: always
    container_name: gms-proj-minio
    image: bitnami/minio:latest
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # fix some crashing issues
      MINIO_SKIP_CLIENT: 'yes'
      MINIO_SCHEME: ${MINIO_SCHEME}
    # command: server /data --console-address ":9001"
    # command: server --address ":9000" --console-address ":9001" /data    
    ports:
      - '9000:9000'
      - '9001:9001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_storage:/data
    networks:
      - gms-proj-net

volumes:
  gms-proj-data:
  minio_storage:

networks:
  gms-proj-net:
    name: gms-proj-net
    external: true