import { type ELEMENTS } from "./elements";

export const ELEMENTS_TITLE: Record<keyof typeof ELEMENTS, React.ReactNode> = {
  lithium: <span>Li<sup>+</sup></span>,
  rubidium: <span>Rb<sup>+</sup></span>,
  cesium: <span>Cs<sup>+</sup></span>,
  boron: <span>B</span>,
  iodine: <span>I<sup>-</sup></span>,
  sodium: <span>Na<sup>+</sup></span>,
  calcium: <span>Ca<sup>2+</sup></span>,
  magnesium: <span>Mg<sup>2+</sup></span>,
  potassium: <span>K<sup>+</sup></span>,
  chlorine: <span>Cl<sup>-</sup></span>,
  bromine: <span>Br<sup>-</sup></span>,
  strontium: <span>Sr<sup>2+</sup></span>,
  barium: <span>Ba<sup>2+</sup></span>,
  aluminum: <span>Al<sup>3+</sup></span>,
  selenium: <span>Se<sup>2+</sup></span>,
  silicon: <span>Si</span>,
  manganese: <span>Mn<sup>2+</sup></span>,
  copper: <span>Сu<sup>2+</sup></span>,
  zinc: <span>Zn<sup>2+</sup></span>,
  silver: <span>Ag</span>,
  tungsten: <span>W</span>,
  titanium: <span>Ti</span>,
  vanadium: <span>V</span>,
  chromium: <span>Cr</span>,
  cobalt: <span>Co</span>,
  nickel: <span>Ni</span>,
  arsenic: <span>As</span>,
  molybdenum: <span>Mo</span>,
  plumbum: <span>Pb</span>,
  bismuth: <span>Bi</span>,
  sulfateIon: <span>SO<sub>4</sub><sup>2-</sup></span>,
  bicarbonate: <span>HCO<sub>3</sub><sup>-</sup></span>,
  carbonateIon: <span>CO<sub>3</sub><sup>-2</sup></span>,
  ammonium: <span>NH<sub>4</sub><sup>+</sup></span>,
  fluorine: <span>F<sup>-</sup></span>,
  nitrogenDioxide: <span>NO<sub>2</sub><sup>-</sup></span>,
  nitrate: <span>NO<sub>3</sub><sup>-</sup></span>,
  phosphate: <span>PO<sub>4</sub><sup>3-</sup></span>,
  ferrum: <span>Fe<sup>(общ)</sup></span>
}
