const data = {
  and: "и",
  or: "или",
  id: "ID",
  name: "Название",
  email: "Email",
  role: "Роль",
  unknown: "Неизвестный",
  user: "Пользователь",
  guest: "Гость",
  admin: "Админ",
  "super-admin": "Супер-Админ",
  companyId: "ID Компании",
  companyName: "Компания",
  clusterId: "ID Кластера",
  clusterName: "Кластер",
  fieldId: "ID Месторождения",
  fieldName: "Месторождение",
  licensedAreaId: "ID Лицензионного участка",
  licensedAreaName: "Лицензионный участок",
  areaId: "ID Лицензионного участка",
  areaName: "Лицензионный участок",
  expires: "Истекает",
  bush: "Куст",
  hole: "Скважина",
  plast: "Пласт",
  horizon: "Горизонт",
  retinue: "Свита",
  occurrenceIntervalStart: "Интервал залегания (м) от",
  occurrenceIntervalEnd: "Интервал залегания (м) до",
  occurrenceInterval: "Интервал залегания (м)",
  samplingDate: "Дата отбора пробы",
  analysisDate: "Дата анализа",
  protocol: "№ протокола (лаборатория)",
  protocolUrl: "Ссылка на протокол",
  sampleCode: "Шифр пробы (лаборатория)",
  pHydrogen: "pH",
  density: "p (кг/м³)",
  mineralization: "Минерализация (мг/дм³)",
  lithium: "Li+",
  rubidium: "Rb+",
  cesium: "Cs+",
  boron: "B",
  iodine: "I-",
  sodium: "Na+",
  calcium: "Ca2+",
  magnesium: "Mg2+",
  potassium: "K+",
  chlorine: "Cl-",
  bromine: "Br-",
  strontium: "Sr2+",
  barium: "Ba2+",
  aluminum: "Al3+",
  selenium: "Se2+",
  silicon: "Si",
  manganese: "Mn2+",
  copper: "Cu2+",
  zinc: "Zn2+",
  silver: "Ag",
  tungsten: "W",
  titanium: "Ti",
  vanadium: "V",
  chromium: "Cr",
  cobalt: "Co",
  nickel: "Ni",
  arsenic: "As",
  molybdenum: "Mo",
  plumbum: "Pb",
  bismuth: "Bi",
  sulfateIon: "SO42-",
  bicarbonate: "HCO3-",
  carbonateIon: "CO32-",
  ammonium: "NH4+",
  fluorine: "F-",
  nitrogenDioxide: "NO2-",
  nitrate: "NO3-",
  phosphate: "PO43-",
  ferrum: "Fe(общ)",
  rigidity: "Жесткость, ºЖ",
  alkalinity: "Общая щелочность, ммоль/дм³",
  electricalConductivity: "Удельная электропроводимость, мСм/см",
  suspendedSolids: "Взвешенные вещества, мг/дм³",
  dryResidue: "Сухой остаток",
  analysisPlace: "Место анализа",
  note: "Примечание"
}

export default data