export type DataTableConfig = typeof dataTableConfig

export const dataTableConfig = {
  textOperators: [
    { label: "Содержит", value: "iLike" as const },
    { label: "Не содержит", value: "notILike" as const },
    { label: "=", value: "eq" as const },
    { label: "!=", value: "ne" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "=", value: "eq" as const },
    { label: "!=", value: "ne" as const },
    { label: "<", value: "lt" as const },
    { label: "<=", value: "lte" as const },
    { label: ">", value: "gt" as const },
    { label: ">=", value: "gte" as const },
  ],
  dateOperators: [
    { label: "=", value: "eq" as const },
    { label: "!=", value: "ne" as const },
    { label: "<", value: "lt" as const },
    { label: ">", value: "gt" as const },
    { label: "<=", value: "lte" as const },
    { label: ">=", value: "gte" as const },
    { label: "Между", value: "isBetween" as const },
    { label: "Относительно сегодня", value: "isRelativeToToday" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "=", value: "eq" as const },
    { label: "!=", value: "ne" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "=", value: "eq" as const },
    { label: "!=", value: "ne" as const },
  ],
  joinOperators: [
    { label: "И", value: "and" as const },
    { label: "Или", value: "or" as const },
  ],
  sortOrders: [
    { label: "Asc", value: "asc" as const },
    { label: "Desc", value: "desc" as const },
  ],
  columnTypes: [
    "text",
    "number",
    "date",
    "boolean",
    "select",
    "multi-select",
  ] as const,
  globalOperators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
    "and",
    "or",
  ] as const,
}